apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmclarity.ui.name" . }}
  labels: {{- include "vmclarity.ui.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "vmclarity.ui.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      labels: {{- include "vmclarity.ui.labels.standard" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: {{ include "vmclarity.images.image" ( dict "imageRoot" .Values.ui.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy | quote }}
