{{/*
Headless Service does not include a ClusterIP so that the DNS record includes
all Pod addresses. This makes it possible for the API Gateway to load balance
all replicas instead of relying on kube-proxy to do it.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ui-hl" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
