openapi: 3.0.1

info:
  title: VMClarity UI APIs
  version: 1.0.0

servers:
  - url: /ui/api

paths:
  /dashboard/riskiestRegions:
    get:
      summary: Get a list of riskiest regions for the dashboard.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskiestRegions'
        default:
          $ref: '#/components/responses/UnknownError'

  /dashboard/riskiestAssets:
    get:
      summary: Get a list of riskiest assets for the dashboard.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskiestAssets'
        default:
          $ref: '#/components/responses/UnknownError'

  /dashboard/findingsTrends:
    get:
      summary: Get a list of finding trends for all finding types.
      parameters:
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindingsTrends'
        default:
          $ref: '#/components/responses/UnknownError'

components:
  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          readOnly: true
      description: An object that is returned in all cases of failures.

    FindingsTrends:
      description: List of finding trends for all finding types.
      type: array
      items:
        $ref: '#/components/schemas/FindingTrends'
      readOnly: true

    FindingTrends:
      description: List of the total number of findings per time slot for the specific findingType.
      type: object
      properties:
        findingType:
          $ref: '#/components/schemas/FindingType'
        trends:
          type: array
          items:
            $ref: '#/components/schemas/FindingTrend'
          readOnly: true

    FindingTrend:
      description: Represents the total number of findings in the time slot (between startTime and endTime).
      type: object
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        count:
          type: integer

    FindingType:
      type: string
      enum:
        - PACKAGE
        - VULNERABILITY
        - MALWARE
        - SECRET
        - MISCONFIGURATION
        - ROOTKIT
        - EXPLOIT

    RiskiestRegions:
      type: object
      properties:
        regions:
          type: array
          description: List of regions with the findings that was found on them. 
            Regions with no findings will not be reported.
          items:
            $ref: '#/components/schemas/RegionFindings'
          readOnly: true

    RegionFindings:
      type: object
      description: Total findings for a region
      properties:
        regionName:
          type: string
        findingsCount:
          $ref: '#/components/schemas/FindingsCount'

    FindingsCount:
      type: object
      description: total count of each finding type
      properties:
        vulnerabilities:
          type: integer
        malware:
          type: integer
        rootkits:
          type: integer
        secrets:
          type: integer
        misconfigurations:
          type: integer
        exploits:
          type: integer

    RiskiestAssets:
      type: object
      properties:
        vulnerabilities:
          type: array
          description: Top 5 riskiest assets sorted by vulnerabilities
          items:
            $ref: '#/components/schemas/VulnerabilityRiskyAsset'
          readOnly: true
        malware:
          type: array
          description: Top 5 riskiest assets sorted by malware count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        rootkits:
          type: array
          description: Top 5 riskiest assets sorted by rootkits count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        secrets:
          type: array
          description: Top 5 riskiest assets sorted by secrets count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        misconfigurations:
          type: array
          description: Top 5 riskiest assets sorted by misconfigurations count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        exploits:
          type: array
          description: Top 5 riskiest assets sorted by exploits count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true

    RiskyAsset:
      type: object
      description: Total number of findings for an asset
      properties:
        assetInfo:
          $ref: '#/components/schemas/AssetInfo'
        count:
          type: integer

    VulnerabilityRiskyAsset:
      type: object
      description: Total number of vulnerability findings for an asset
      properties:
        assetInfo:
          $ref: '#/components/schemas/AssetInfo'
        criticalVulnerabilitiesCount:
          type: integer
        highVulnerabilitiesCount:
          type: integer
        mediumVulnerabilitiesCount:
          type: integer
        lowVulnerabilitiesCount:
          type: integer
        negligibleVulnerabilitiesCount:
          type: integer

    AssetInfo:
      type: object
      properties:
        name:
          type: string
        location:
          type: string
        type:
          $ref: '#/components/schemas/AssetType'

    AssetType:
      type: string
      enum:
        - 'AWS EC2 Instance'

  responses:
    UnknownError:
      description: Unknown error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'

  parameters:
    exampleFilter:
      name: "example"
      in: query
      schema:
        type: string

    startTime:
      name: 'startTime'
      in: query
      schema:
        type: string
        format: date-time
      required: true

    endTime:
      name: 'endTime'
      in: query
      schema:
        type: string
        format: date-time
      required: true
