openapi: 3.0.1

info:
  title: VMClarity UI APIs
  version: 1.0.0

servers:
  - url: /ui/api

paths:
  /dashboard/riskiestRegions:
    get:
      summary: Get a list of riskiest regions for the dashboard.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskiestRegions'
        default:
          $ref: '#/components/responses/UnknownError'

  /dashboard/riskiestAssets:
    get:
      summary: Get a list of riskiest assets for the dashboard.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskiestAssets'
        default:
          $ref: '#/components/responses/UnknownError'

components:
  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          readOnly: true
      description: An object that is returned in all cases of failures.

    RiskiestRegions:
      type: object
      properties:
        regions:
          type: array
          description: List of regions with the findings that was found on them. 
            Regions with no findings will not be reported.
          items:
            $ref: '#/components/schemas/RegionFindings'
          readOnly: true

    RegionFindings:
      type: object
      description: Total findings for a region
      properties:
        regionName:
          type: string
        findingsCount:
          $ref: '#/components/schemas/FindingsCount'

    FindingsCount:
      type: object
      description: total count of each finding type
      properties:
        vulnerabilities:
          type: integer
        malware:
          type: integer
        rootkits:
          type: integer
        secrets:
          type: integer
        misconfigurations:
          type: integer
        exploits:
          type: integer

    RiskiestAssets:
      type: object
      properties:
        vulnerabilities:
          type: array
          description: Top 5 assets sorted by max vulnerabilites count
          items:
            $ref: '#/components/schemas/VulnerabilityRiskyAsset'
          readOnly: true
        malware:
          type: array
          description: Top 5 assets sorted by max malware count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        rootkits:
          type: array
          description: Top 5 assets sorted by max rootkits count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        secrets:
          type: array
          description: Top 5 assets sorted by max secrets count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        misconfigurations:
          type: array
          description: Top 5 assets sorted by max misconfigurations count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true
        exploits:
          type: array
          description: Top 5 assets sorted by max exploits count
          items:
            $ref: '#/components/schemas/RiskyAsset'
          readOnly: true

    RiskyAsset:
      type: object
      description: Total findings for an asset
      properties:
        assetInfo:
          $ref: '#/components/schemas/AssetInfo'
        count:
          type: integer

    VulnerabilityRiskyAsset:
      type: object
      description: Total vulnerabilities findings for an asset
      properties:
        assetInfo:
          $ref: '#/components/schemas/AssetInfo'
        count:
          $ref: '#/components/schemas/VulnerabilityCount'

    VulnerabilityCount:
      type: object
      properties:
        criticalVulnerabilitiesCount:
          type: integer
        highVulnerabilitiesCount:
          type: integer
        mediumVulnerabilitiesCount:
          type: integer
        lowVulnerabilitiesCount:
          type: integer
        negligibleVulnerabilitiesCount:
          type: integer

    AssetInfo:
      type: object
      properties:
        name:
          type: string
        location:
          type: string
        type:
          $ref: '#/components/schemas/AssetType'

    AssetType:
      type: string
      enum:
        - 'AWS EC2 Instance'

  responses:
    UnknownError:
      description: Unknown error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'

  parameters:
    exampleFilter:
      name: "example"
      in: query
      schema:
        type: string
