apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmclarity.ui.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.ui.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector: {{- include "vmclarity.ui.labels.matchLabels" . | nindent 4 }}
