apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmclarity.freshclamMirror.name" . }}
  labels: {{- include "vmclarity.freshclamMirror.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "vmclarity.freshclamMirror.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.freshclamMirror.replicaCount }}
  template:
    metadata:
      labels: {{- include "vmclarity.freshclamMirror.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.freshclamMirror.affinity }}
      affinity: {{- .Values.freshclamMirror.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.freshclamMirror.nodeSelector }}
      nodeSelector: {{- .Values.freshclamMirror.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.freshclamMirror.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.freshclamMirror.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.freshclamMirror.tolerations }}
      tolerations: {{- .Values.freshclamMirror.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: freshclam-mirror
          image: {{ include "vmclarity.images.image" ( dict "imageRoot" .Values.freshclamMirror.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.freshclamMirror.image.pullPolicy | quote }}
          {{- if .Values.freshclamMirror.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.freshclamMirror.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.freshclamMirror.resources }}
          resources: {{- toYaml .Values.freshclamMirror.resources | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ include "vmclarity.freshclamMirror.serviceAccountName" . }}
