version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    aws-sdk:
      patterns:
        - "github.com/aws/aws-sdk-go-v2"
        - "github.com/aws/aws-sdk-go-v2/*"
        - "github.com/aws/smithy-go"
    azure-sdk:
      patterns:
        - "github.com/Azure/azure-sdk-for-go/sdk/*"
    google-sdk:
      patterns:
        - "cloud.google.com/go/*"
    containrd:
      patterns:
        - "github.com/containerd/*"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
