version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    aws-sdk:
      patterns:
        - "github.com/aws/aws-sdk-go-v2"
        - "github.com/aws/aws-sdk-go-v2/*"
        - "github.com/aws/smithy-go"
    azure-sdk:
      patterns:
        - "github.com/Azure/azure-sdk-for-go/sdk/*"
    google-sdk:
      patterns:
        - "cloud.google.com/go/*"
    containerd:
      patterns:
        - "github.com/containerd/*"
    k8s:
      patterns:
        - "k8s.io/api"
        - "k8s.io/apimachinery"
        - "k8s.io/client-go"
    docker:
      patterns:
        - "github.com/docker/docker"
        - "github.com/docker/cli"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
