export const FINDINGS_ICON_MAPPING = {
    PACKAGES: ICON_NAMES.PACKAGE,
    EXPLOITS: ICON_NAMES.BOMB,
    MISCONFIGURATIONS: ICON_NAMES.COG,
    SECRETS: ICON_NAMES.KEY,
    MALWARE: ICON_NAMES.BUG,
    ROOTKITS: ICON_NAMES.GHOST
}