builds:
  -
    id: "cli"
    dir: cli
    binary: vmclarity-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
      - "-X github.com/openclarity/vmclarity/pkg/version.Version={{ .Version }}"
      - "-X github.com/openclarity/vmclarity/pkg/version.CommitHash={{.Commit}}"
      - "-X github.com/openclarity/vmclarity/pkg/version.BuildTimestamp={{.Timestamp}}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  -
    id: "cli"
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

    # Additional files/template/globs we want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

# Change the default artifacts folder
dist: goreleaser_artifacts

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^workflow:'
      - Merge pull request
      - Merge remote-tracking branch

release:
  extra_files:
    - glob: ./installation/aws/VmClarity.cfn
