# syntax=docker/dockerfile:1@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e

FROM --platform=$BUILDPLATFORM node:20-slim AS site-build

WORKDIR /src

COPY --link ./ui /src

RUN --mount=type=cache,target=/src/node_modules \
    npm install

RUN --mount=type=cache,target=/src/node_modules \
    npm run build

FROM nginx:1.27.0@sha256:9c367186df9a6b18c6735357b8eb7f407347e84aea09beb184961cb83543d46e

COPY --from=site-build ["/src/build", "/usr/share/nginx/html"]

COPY --link ["ui/nginx.conf", "/etc/nginx/conf.d/default.conf"]
