openapi: 3.0.1
info:
  title: Scanner Plugin API
  version: 1.0.0
paths:
  /healthz:
    get:
      summary: Check the scanner plugin's health.
      operationId: GetHealthz
      responses:
        200:
          description: The scanner is healthy and can start receiving requests.
        503:
          description: The scanner is not healthy and cannot start receiving requests.
  /metadata:
    get:
      summary: Get metadata from the scanner plugin.
      operationId: GetMetadata
      responses:
        200:
          description: Scanner metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
  /config:
    post:
      summary: Post config to the scanner plugin and start scanner.
      operationId: PostConfig
      responses:
        201:
          description: A new scan has been created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  scanID:
                    type: string
                    description: The ID of the scan that has been created.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
  /status:
    get:
      summary: Get the status of the scanner.
      operationId: GetStatus
      responses:
        200:
          description: The status of the scanner.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Status:
      type: object
      required:
        - state
        - lastTransitionTime
      properties:
        state:
          description: |
            Describes the status of scanner.
            | Status         | Description                                                   |
            | -------------- | ------------------------------------------------------------- |
            | NotReady       | Initial state when the scanner container starts               |
            | Ready          | Scanner setup is complete and it is ready to receive requests |
            | Running        | Scanner config was received and the scanner is running        |
            | Failed         | Scanner failed                                                |
            | Done           | Scanner is completed successfully                             |
          type: string
          enum:
            - NotReady
            - Ready
            - Running
            - Failed
            - Done
        message:
          description: Human readable message.
          type: string
        lastTransitionTime:
          description: Last date time when the status has changed.
          type: string
          format: date-time

    Config:
      type: object
      description: Describes a scanner config.
      properties:
        file:
          type: string
          description: |
            The file with the configuration required by the scanner plugin. This is a path on the filesystem to the config file.
        inputDir:
          type: string
          description: |
            The directory which should be scanned by the scanner plugin.
        outputDir:
          type: string
          description: |
            The directory where the scanner plugin should store it's findings.
        timeoutSeconds:
          type: integer
          minimum: 0
          description: |
            The maximum time in seconds that a scan started from this config
            should run for before being automatically aborted.

    Metadata:
      type: object
      description: Describes the scanner plugin.
      properties:
        apiVersion:
          type: string