{{- if .Values.trivyServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmclarity.trivyServer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.trivyServer.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.trivyServer.serviceAccount.automountServiceAccountToken }}
{{- end -}}
