{{- if .Values.uibackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmclarity.uibackend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.uibackend.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.uibackend.serviceAccount.automountServiceAccountToken }}
{{- end -}}
