// Package plugin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package plugin

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Post config to the scanner plugin and start scanner.
	// (POST /config)
	PostConfig(ctx echo.Context) error
	// Check the scanner plugin's health.
	// (GET /healthz)
	GetHealthz(ctx echo.Context) error
	// Get metadata from the scanner plugin.
	// (GET /metadata)
	GetMetadata(ctx echo.Context) error
	// Get the status of the scanner.
	// (GET /status)
	GetStatus(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostConfig(ctx)
	return err
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// GetMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetMetadata(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMetadata(ctx)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/config", wrapper.PostConfig)
	router.GET(baseURL+"/healthz", wrapper.GetHealthz)
	router.GET(baseURL+"/metadata", wrapper.GetMetadata)
	router.GET(baseURL+"/status", wrapper.GetStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RW34/bNgz+VwhtQF9cJ7diL3m7NVsbYBsOvWAvuz4oNh2rsyVPpJtlvfzvAyXblx+6",
	"ux6w+iWORX38SJEf9UUVru2cRcukFl8UFTW2Ory+dbYyW3krkQpvOjbOqoVahn8bJNBAhbYWPRTBNleZ",
	"6rzr0LPBgFGZBi8R1jWCrMDOcA1c47C/91oswOPfvfFYwmYfVkcvXdNvjc1hXRsCI/47zTU4G6wEkfbE",
	"2AK7I9SwkN9ZlSned6gWitgbu1WHTBnb9bw0Ps2xNB4Ldn4Pu9oUNVDt+qaEzcjoMYJpX67nr3WGHhO4",
	"o39i5xEMvyKojC2N3dIjLtm06Hq+xcLZktJ+W/2PafsWxBbESTQGrjUPJwzE2jOWUHnXAkv2Y2rv7EDJ",
	"9xYq52GDlXDboLFb0D27VrMpdNPsQW+cYESmrbHiVC3mE2tjGbfo1eEwfXKbT1iwBPKz985/QOqcpURB",
	"XVuItpG1IfDIvZcTElYaKm0aLOH6ZhWKC4kva7VFIr0N6GeJTDH6DVmXmvVT/ZEojQuvujN/oKew9asc",
	"37LmPmw9BWo08dprS0Z4rE2byNOvmhhKzRhPe1djbB0KmFBrgqLWdoulEK2cbzWrhZIdr2VHqsaO0nbq",
	"7H3faullXepNgzDY5SkM8Y/PZjKSdNWY0/zO3kNMB4zPPSwfIODlz71gvj554PzDC5+I+bvjD6jL/cRz",
	"ZQ0b3YSwjo/iQVFZG3kLzUcpnseAAfN22EzIfQehTduuQUbQtgQzdIZsYgceCzSfcWwIGjB7a6V5LzAH",
	"Md1pGneWAfWYtMCf7RfMX2L3XWJWpwsvOaOlswip2I+iLoH6okCiqhcFegZTZQqtaNKfajwslanpN8al",
	"MhWjUZkSCupjlmjacYAJVqztLNWfHy/a+xBmUuWCFhiW4anGwG7iELi+WalMfR41Q13l83we5kuHVndG",
	"LdSbfJ5fidJoroM2zIpplneOWH5FOsK0XZVqoW4c8TDvI3sk/smVe7GUSkTLUay6xhRh2+wTRcmKNwZ5",
	"+95jpRbqu9nDlWI23CdmA/jhNDvsewwforAHrj/Mr17k9VQFpRJXy/SkWy1FPMZ6jaNCJG+DaKHwqDnq",
	"3rMiLJ/OBhBY3EXYS0Qxp75ttd8PqR6babinnI156arQ9JPQBYhZjbrh+l8JbouJQ3yH/H4wucjpPJ2S",
	"o8aN6PvgfZr5Q6tLQ48ykUut/Th/8yygdXwOKp+ewD3J09sai78S6Xk1Uh2y0h4N4sfSMg3rdF7+lwqf",
	"fCTKY2zhket5rO+Qp7XxknV5dQjh0jT+Hwt2uCB8w1AHD4lA1ydz+iiIVMT8lPHh8F8AAAD//yQygQqb",
	"DAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
