apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmclarity.orchestrator.name" . }}
  labels: {{- include "vmclarity.orchestrator.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "vmclarity.orchestrator.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.orchestrator.replicaCount }}
  template:
    metadata:
      labels: {{- include "vmclarity.orchestrator.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.orchestrator.affinity }}
      affinity: {{- .Values.orchestrator.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.orchestrator.nodeSelector }}
      nodeSelector: {{- .Values.orchestrator.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.orchestrator.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.orchestrator.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.orchestrator.tolerations }}
      tolerations: {{- .Values.orchestrator.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: orchestrator
          image: {{ include "vmclarity.images.image" ( dict "imageRoot" .Values.orchestrator.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy | quote }}
          {{- if .Values.orchestrator.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.orchestrator.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args:
            - run
            - --log-level
            - {{ .Values.orchestrator.logLevel }}
          env:
            # Host for the VMClarity backend server
            - name: APISERVER_HOST
              value: {{ include "vmclarity.apiserver.name" . }}
            # Port number for the VMClarity backend server
            - name: APISERVER_PORT
              value: "8888"

            {{/* TODO(sambetts) Add provider configuration logic in here */}}
