{{- if .Values.orchestrator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmclarity.orchestrator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.orchestrator.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.orchestrator.serviceAccount.automountServiceAccountToken }}
{{- end -}}
