### get scanner info
GET http://localhost:8765/scanner

### create scan
POST http://localhost:8765/scans
Content-Type: application/json

{
  "inputs": [
    {
      "type": "IMAGE",
      "path": "nginx"
    }
  ],
  "timeoutSeconds": 650
}

### get all scans
GET http://localhost:8765/scans

### get pending scans
GET http://localhost:8765/scans?state=pending

### get specific scan
GET http://localhost:8765/scan/b87741ca-ec90-4fa5-b76e-fabc007d5f8b

### get specific scan result
GET http://localhost:8765/scan/014222b8-7b95-440e-beb6-69397ad42eb2/result

### stop specific scan
POST http://localhost:8765/scan/b87741ca-ec90-4fa5-b76e-fabc007d5f8b/stop

### delete scan
DELETE http://localhost:8765/scan/44a31da4-cb99-4141-90dd-d546010f97d5
