{{- if .Values.swaggerUI.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmclarity.swaggerUI.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.swaggerUI.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.swaggerUI.serviceAccount.automountServiceAccountToken }}
{{- end -}}
