export const ICON_NAMES = {
    DASHBOARD: "dashboard",
    SCANS: "scans",
    DUPLICATE: "duplicate",
    X_MARK: "x-mark",
    SORT: "sort",
    CHEVRON_RIGHT: "chevron-right",
    CHEVRON_RIGHT_DOUBLE: "chevron-right-double",
    ARROW_LEFT: "arrow-left",
    PLUS: "plus",
    MINUS: "minus",
    PLAY: "play",
    STOP: "stop",
    DELETE: "delete",
    EDIT: "edit",
    INFO: "info",
    SHIELD: "shield",
    WARNING: "warning",
    LOCK: "lock",
    COG: "cog",
    KEY: "key",
    BUG: "bug",
    GHOST: "ghost",
    REFRESH: "refresh"
}