apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmclarity.apiserver.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.apiserver.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector: {{- include "vmclarity.apiserver.labels.matchLabels" . | nindent 4 }}
