{{- if .Values.crDiscoveryServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmclarity.crDiscoveryServer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.crDiscoveryServer.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.crDiscoveryServer.serviceAccount.automountServiceAccountToken }}
{{- end -}}
