imports:
- path: vmclarity.py

resources:
- name: vmclarity
  type: vmclarity.py
  properties:
    region: us-central1
    zone: us-central1-f
    machineType: e2-standard-2
    sshPublicKey: <SSH Public Key>

outputs:
  - name: vmclarity-ip
    value: $(ref.vmclarity.ip)
