global:
  imageRegistry: ""

apiserver:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/vmclarity-apiserver
    tag: latest
    pullPolicy: IfNotPresent

  logLevel: info

orchestrator:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/vmclarity-orchestrator
    tag: latest
    pullPolicy: IfNotPresent

  logLevel: info

ui:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/vmclarity-ui
    tag: latest
    pullPolicy: IfNotPresent

uibackend:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/vmclarity-uibackend
    tag: latest
    pullPolicy: IfNotPresent

  logLevel: info

gateway:
  replicas: 1

  image:
    registry: docker.io
    repository: library/nginx
    tag: 1.25.1
    pullPolicy: IfNotPresent

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 14.6.0-debian-11-r31
    pullPolicy: IfNotPresent

  auth:
    # existingSecret: vmclarity-postgres-credentials
    username: vmclarity
    password: password1
    database: vmclarity

  service:
    ports:
      postgresql: 5432

exploitDBServer:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/exploit-db-server
    tag: v0.2.3
    pullPolicy: IfNotPresent

trivyServer:
  replicas: 1

  image:
    registry: docker.io
    repository: aquasec/trivy
    tag: 0.41.0
    pullPolicy: IfNotPresent

grypeServer:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/grype-server
    tag: v0.4.0
    pullPolicy: IfNotPresent

  logLevel: info

freshclamMirror:
  replicas: 1

  image:
    registry: ghcr.io
    repository: openclarity/freshclam-mirror
    tag: v0.1.0
    pullPolicy: IfNotPresent
