#!/usr/bin/env bash

## Script vars
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
PLUGINPATH="$(realpath $SCRIPTPATH/../../..)"
PYTHONSDKPATH="$(realpath $SCRIPTPATH/..)"

## Generate code
echo "Generating Python server code from $PLUGINPATH"
docker run --rm \
  -v ${PLUGINPATH}:/src openapitools/openapi-generator-cli generate \
  -i /src/openapi.yaml \
  -g python-flask \
  -o /src/sdk/python/generated \
  --package-name "plugin" \
  --additional-properties legacyDiscriminatorBehavior=false

## Remove unused generated code
rm -rf $PYTHONSDKPATH/generated/plugin/controllers
rm -rf $PYTHONSDKPATH/generated/plugin/test
rm -rf $PYTHONSDKPATH/generated/plugin/openapi
rm -rf $PYTHONSDKPATH/generated/plugin/__main__.py

## Move autogenerated code
cp -R $PYTHONSDKPATH/generated/plugin/* $PYTHONSDKPATH/plugin/
cp $PYTHONSDKPATH/generated/.dockerignore $PYTHONSDKPATH/
cp $PYTHONSDKPATH/generated/.gitignore $PYTHONSDKPATH/
cp $PYTHONSDKPATH/generated/requirements.txt $PYTHONSDKPATH/
cp $PYTHONSDKPATH/generated/setup.py $PYTHONSDKPATH/

## Cleanup
rm -rf $PYTHONSDKPATH/generated
