// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTestParams creates a new GetTestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTestParams() *GetTestParams {
	return &GetTestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestParamsWithTimeout creates a new GetTestParams object
// with the ability to set a timeout on a request.
func NewGetTestParamsWithTimeout(timeout time.Duration) *GetTestParams {
	return &GetTestParams{
		timeout: timeout,
	}
}

// NewGetTestParamsWithContext creates a new GetTestParams object
// with the ability to set a context for a request.
func NewGetTestParamsWithContext(ctx context.Context) *GetTestParams {
	return &GetTestParams{
		Context: ctx,
	}
}

// NewGetTestParamsWithHTTPClient creates a new GetTestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTestParamsWithHTTPClient(client *http.Client) *GetTestParams {
	return &GetTestParams{
		HTTPClient: client,
	}
}

/* GetTestParams contains all the parameters to send to the API endpoint
   for the get test operation.

   Typically these are written to a http.Request.
*/
type GetTestParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestParams) WithDefaults() *GetTestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get test params
func (o *GetTestParams) WithTimeout(timeout time.Duration) *GetTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get test params
func (o *GetTestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get test params
func (o *GetTestParams) WithContext(ctx context.Context) *GetTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get test params
func (o *GetTestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get test params
func (o *GetTestParams) WithHTTPClient(client *http.Client) *GetTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get test params
func (o *GetTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
