// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/vmclarity/api/client/models"
)

// PostInstancesRootkitScanIDReader is a Reader for the PostInstancesRootkitScanID structure.
type PostInstancesRootkitScanIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInstancesRootkitScanIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostInstancesRootkitScanIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPostInstancesRootkitScanIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostInstancesRootkitScanIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostInstancesRootkitScanIDCreated creates a PostInstancesRootkitScanIDCreated with default headers values
func NewPostInstancesRootkitScanIDCreated() *PostInstancesRootkitScanIDCreated {
	return &PostInstancesRootkitScanIDCreated{}
}

/*
PostInstancesRootkitScanIDCreated describes a response with status code 201, with default header values.

Instance rootkit scan successfully reported.
*/
type PostInstancesRootkitScanIDCreated struct {
}

// IsSuccess returns true when this post instances rootkit scan Id created response has a 2xx status code
func (o *PostInstancesRootkitScanIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post instances rootkit scan Id created response has a 3xx status code
func (o *PostInstancesRootkitScanIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post instances rootkit scan Id created response has a 4xx status code
func (o *PostInstancesRootkitScanIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post instances rootkit scan Id created response has a 5xx status code
func (o *PostInstancesRootkitScanIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post instances rootkit scan Id created response a status code equal to that given
func (o *PostInstancesRootkitScanIDCreated) IsCode(code int) bool {
	return code == 201
}

func (o *PostInstancesRootkitScanIDCreated) Error() string {
	return fmt.Sprintf("[POST /instances/rootkitScan/{id}][%d] postInstancesRootkitScanIdCreated ", 201)
}

func (o *PostInstancesRootkitScanIDCreated) String() string {
	return fmt.Sprintf("[POST /instances/rootkitScan/{id}][%d] postInstancesRootkitScanIdCreated ", 201)
}

func (o *PostInstancesRootkitScanIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInstancesRootkitScanIDNotFound creates a PostInstancesRootkitScanIDNotFound with default headers values
func NewPostInstancesRootkitScanIDNotFound() *PostInstancesRootkitScanIDNotFound {
	return &PostInstancesRootkitScanIDNotFound{}
}

/*
PostInstancesRootkitScanIDNotFound describes a response with status code 404, with default header values.

Instance not found.
*/
type PostInstancesRootkitScanIDNotFound struct {
}

// IsSuccess returns true when this post instances rootkit scan Id not found response has a 2xx status code
func (o *PostInstancesRootkitScanIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post instances rootkit scan Id not found response has a 3xx status code
func (o *PostInstancesRootkitScanIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post instances rootkit scan Id not found response has a 4xx status code
func (o *PostInstancesRootkitScanIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post instances rootkit scan Id not found response has a 5xx status code
func (o *PostInstancesRootkitScanIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post instances rootkit scan Id not found response a status code equal to that given
func (o *PostInstancesRootkitScanIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *PostInstancesRootkitScanIDNotFound) Error() string {
	return fmt.Sprintf("[POST /instances/rootkitScan/{id}][%d] postInstancesRootkitScanIdNotFound ", 404)
}

func (o *PostInstancesRootkitScanIDNotFound) String() string {
	return fmt.Sprintf("[POST /instances/rootkitScan/{id}][%d] postInstancesRootkitScanIdNotFound ", 404)
}

func (o *PostInstancesRootkitScanIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInstancesRootkitScanIDDefault creates a PostInstancesRootkitScanIDDefault with default headers values
func NewPostInstancesRootkitScanIDDefault(code int) *PostInstancesRootkitScanIDDefault {
	return &PostInstancesRootkitScanIDDefault{
		_statusCode: code,
	}
}

/*
PostInstancesRootkitScanIDDefault describes a response with status code -1, with default header values.

unknown error
*/
type PostInstancesRootkitScanIDDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// Code gets the status code for the post instances rootkit scan ID default response
func (o *PostInstancesRootkitScanIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this post instances rootkit scan ID default response has a 2xx status code
func (o *PostInstancesRootkitScanIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post instances rootkit scan ID default response has a 3xx status code
func (o *PostInstancesRootkitScanIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post instances rootkit scan ID default response has a 4xx status code
func (o *PostInstancesRootkitScanIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post instances rootkit scan ID default response has a 5xx status code
func (o *PostInstancesRootkitScanIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post instances rootkit scan ID default response a status code equal to that given
func (o *PostInstancesRootkitScanIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PostInstancesRootkitScanIDDefault) Error() string {
	return fmt.Sprintf("[POST /instances/rootkitScan/{id}][%d] PostInstancesRootkitScanID default  %+v", o._statusCode, o.Payload)
}

func (o *PostInstancesRootkitScanIDDefault) String() string {
	return fmt.Sprintf("[POST /instances/rootkitScan/{id}][%d] PostInstancesRootkitScanID default  %+v", o._statusCode, o.Payload)
}

func (o *PostInstancesRootkitScanIDDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PostInstancesRootkitScanIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
