// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/vmclarity/api/client/models"
)

// NewPostInstancesSecretScanIDParams creates a new PostInstancesSecretScanIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostInstancesSecretScanIDParams() *PostInstancesSecretScanIDParams {
	return &PostInstancesSecretScanIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostInstancesSecretScanIDParamsWithTimeout creates a new PostInstancesSecretScanIDParams object
// with the ability to set a timeout on a request.
func NewPostInstancesSecretScanIDParamsWithTimeout(timeout time.Duration) *PostInstancesSecretScanIDParams {
	return &PostInstancesSecretScanIDParams{
		timeout: timeout,
	}
}

// NewPostInstancesSecretScanIDParamsWithContext creates a new PostInstancesSecretScanIDParams object
// with the ability to set a context for a request.
func NewPostInstancesSecretScanIDParamsWithContext(ctx context.Context) *PostInstancesSecretScanIDParams {
	return &PostInstancesSecretScanIDParams{
		Context: ctx,
	}
}

// NewPostInstancesSecretScanIDParamsWithHTTPClient creates a new PostInstancesSecretScanIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostInstancesSecretScanIDParamsWithHTTPClient(client *http.Client) *PostInstancesSecretScanIDParams {
	return &PostInstancesSecretScanIDParams{
		HTTPClient: client,
	}
}

/*
PostInstancesSecretScanIDParams contains all the parameters to send to the API endpoint

	for the post instances secret scan ID operation.

	Typically these are written to a http.Request.
*/
type PostInstancesSecretScanIDParams struct {

	// Body.
	Body *models.InstanceSecretScan

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post instances secret scan ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInstancesSecretScanIDParams) WithDefaults() *PostInstancesSecretScanIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post instances secret scan ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInstancesSecretScanIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) WithTimeout(timeout time.Duration) *PostInstancesSecretScanIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) WithContext(ctx context.Context) *PostInstancesSecretScanIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) WithHTTPClient(client *http.Client) *PostInstancesSecretScanIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) WithBody(body *models.InstanceSecretScan) *PostInstancesSecretScanIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) SetBody(body *models.InstanceSecretScan) {
	o.Body = body
}

// WithID adds the id to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) WithID(id string) *PostInstancesSecretScanIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post instances secret scan ID params
func (o *PostInstancesSecretScanIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostInstancesSecretScanIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
