// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/vmclarity/api/client/models"
)

// PostInstancesContentAnalysisIDReader is a Reader for the PostInstancesContentAnalysisID structure.
type PostInstancesContentAnalysisIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInstancesContentAnalysisIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostInstancesContentAnalysisIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPostInstancesContentAnalysisIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostInstancesContentAnalysisIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostInstancesContentAnalysisIDCreated creates a PostInstancesContentAnalysisIDCreated with default headers values
func NewPostInstancesContentAnalysisIDCreated() *PostInstancesContentAnalysisIDCreated {
	return &PostInstancesContentAnalysisIDCreated{}
}

/*
PostInstancesContentAnalysisIDCreated describes a response with status code 201, with default header values.

Instance content analysis successfully reported.
*/
type PostInstancesContentAnalysisIDCreated struct {
}

// IsSuccess returns true when this post instances content analysis Id created response has a 2xx status code
func (o *PostInstancesContentAnalysisIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post instances content analysis Id created response has a 3xx status code
func (o *PostInstancesContentAnalysisIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post instances content analysis Id created response has a 4xx status code
func (o *PostInstancesContentAnalysisIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post instances content analysis Id created response has a 5xx status code
func (o *PostInstancesContentAnalysisIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post instances content analysis Id created response a status code equal to that given
func (o *PostInstancesContentAnalysisIDCreated) IsCode(code int) bool {
	return code == 201
}

func (o *PostInstancesContentAnalysisIDCreated) Error() string {
	return fmt.Sprintf("[POST /instances/contentAnalysis/{id}][%d] postInstancesContentAnalysisIdCreated ", 201)
}

func (o *PostInstancesContentAnalysisIDCreated) String() string {
	return fmt.Sprintf("[POST /instances/contentAnalysis/{id}][%d] postInstancesContentAnalysisIdCreated ", 201)
}

func (o *PostInstancesContentAnalysisIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInstancesContentAnalysisIDNotFound creates a PostInstancesContentAnalysisIDNotFound with default headers values
func NewPostInstancesContentAnalysisIDNotFound() *PostInstancesContentAnalysisIDNotFound {
	return &PostInstancesContentAnalysisIDNotFound{}
}

/*
PostInstancesContentAnalysisIDNotFound describes a response with status code 404, with default header values.

Instance not found.
*/
type PostInstancesContentAnalysisIDNotFound struct {
}

// IsSuccess returns true when this post instances content analysis Id not found response has a 2xx status code
func (o *PostInstancesContentAnalysisIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post instances content analysis Id not found response has a 3xx status code
func (o *PostInstancesContentAnalysisIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post instances content analysis Id not found response has a 4xx status code
func (o *PostInstancesContentAnalysisIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post instances content analysis Id not found response has a 5xx status code
func (o *PostInstancesContentAnalysisIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post instances content analysis Id not found response a status code equal to that given
func (o *PostInstancesContentAnalysisIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *PostInstancesContentAnalysisIDNotFound) Error() string {
	return fmt.Sprintf("[POST /instances/contentAnalysis/{id}][%d] postInstancesContentAnalysisIdNotFound ", 404)
}

func (o *PostInstancesContentAnalysisIDNotFound) String() string {
	return fmt.Sprintf("[POST /instances/contentAnalysis/{id}][%d] postInstancesContentAnalysisIdNotFound ", 404)
}

func (o *PostInstancesContentAnalysisIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInstancesContentAnalysisIDDefault creates a PostInstancesContentAnalysisIDDefault with default headers values
func NewPostInstancesContentAnalysisIDDefault(code int) *PostInstancesContentAnalysisIDDefault {
	return &PostInstancesContentAnalysisIDDefault{
		_statusCode: code,
	}
}

/*
PostInstancesContentAnalysisIDDefault describes a response with status code -1, with default header values.

unknown error
*/
type PostInstancesContentAnalysisIDDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// Code gets the status code for the post instances content analysis ID default response
func (o *PostInstancesContentAnalysisIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this post instances content analysis ID default response has a 2xx status code
func (o *PostInstancesContentAnalysisIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post instances content analysis ID default response has a 3xx status code
func (o *PostInstancesContentAnalysisIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post instances content analysis ID default response has a 4xx status code
func (o *PostInstancesContentAnalysisIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post instances content analysis ID default response has a 5xx status code
func (o *PostInstancesContentAnalysisIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post instances content analysis ID default response a status code equal to that given
func (o *PostInstancesContentAnalysisIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PostInstancesContentAnalysisIDDefault) Error() string {
	return fmt.Sprintf("[POST /instances/contentAnalysis/{id}][%d] PostInstancesContentAnalysisID default  %+v", o._statusCode, o.Payload)
}

func (o *PostInstancesContentAnalysisIDDefault) String() string {
	return fmt.Sprintf("[POST /instances/contentAnalysis/{id}][%d] PostInstancesContentAnalysisID default  %+v", o._statusCode, o.Payload)
}

func (o *PostInstancesContentAnalysisIDDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PostInstancesContentAnalysisIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
