// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/vmclarity/api/client/models"
)

// PutInstancesIDReader is a Reader for the PutInstancesID structure.
type PutInstancesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutInstancesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutInstancesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPutInstancesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPutInstancesIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutInstancesIDOK creates a PutInstancesIDOK with default headers values
func NewPutInstancesIDOK() *PutInstancesIDOK {
	return &PutInstancesIDOK{}
}

/*
PutInstancesIDOK describes a response with status code 200, with default header values.

Update Instance successful.
*/
type PutInstancesIDOK struct {
	Payload *models.InstanceInfo
}

// IsSuccess returns true when this put instances Id o k response has a 2xx status code
func (o *PutInstancesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put instances Id o k response has a 3xx status code
func (o *PutInstancesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put instances Id o k response has a 4xx status code
func (o *PutInstancesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put instances Id o k response has a 5xx status code
func (o *PutInstancesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put instances Id o k response a status code equal to that given
func (o *PutInstancesIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *PutInstancesIDOK) Error() string {
	return fmt.Sprintf("[PUT /instances/{id}][%d] putInstancesIdOK  %+v", 200, o.Payload)
}

func (o *PutInstancesIDOK) String() string {
	return fmt.Sprintf("[PUT /instances/{id}][%d] putInstancesIdOK  %+v", 200, o.Payload)
}

func (o *PutInstancesIDOK) GetPayload() *models.InstanceInfo {
	return o.Payload
}

func (o *PutInstancesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstanceInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutInstancesIDNotFound creates a PutInstancesIDNotFound with default headers values
func NewPutInstancesIDNotFound() *PutInstancesIDNotFound {
	return &PutInstancesIDNotFound{}
}

/*
PutInstancesIDNotFound describes a response with status code 404, with default header values.

Instance not found.
*/
type PutInstancesIDNotFound struct {
}

// IsSuccess returns true when this put instances Id not found response has a 2xx status code
func (o *PutInstancesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put instances Id not found response has a 3xx status code
func (o *PutInstancesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put instances Id not found response has a 4xx status code
func (o *PutInstancesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put instances Id not found response has a 5xx status code
func (o *PutInstancesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put instances Id not found response a status code equal to that given
func (o *PutInstancesIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *PutInstancesIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /instances/{id}][%d] putInstancesIdNotFound ", 404)
}

func (o *PutInstancesIDNotFound) String() string {
	return fmt.Sprintf("[PUT /instances/{id}][%d] putInstancesIdNotFound ", 404)
}

func (o *PutInstancesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutInstancesIDDefault creates a PutInstancesIDDefault with default headers values
func NewPutInstancesIDDefault(code int) *PutInstancesIDDefault {
	return &PutInstancesIDDefault{
		_statusCode: code,
	}
}

/*
PutInstancesIDDefault describes a response with status code -1, with default header values.

unknown error
*/
type PutInstancesIDDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// Code gets the status code for the put instances ID default response
func (o *PutInstancesIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this put instances ID default response has a 2xx status code
func (o *PutInstancesIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put instances ID default response has a 3xx status code
func (o *PutInstancesIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put instances ID default response has a 4xx status code
func (o *PutInstancesIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put instances ID default response has a 5xx status code
func (o *PutInstancesIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put instances ID default response a status code equal to that given
func (o *PutInstancesIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PutInstancesIDDefault) Error() string {
	return fmt.Sprintf("[PUT /instances/{id}][%d] PutInstancesID default  %+v", o._statusCode, o.Payload)
}

func (o *PutInstancesIDDefault) String() string {
	return fmt.Sprintf("[PUT /instances/{id}][%d] PutInstancesID default  %+v", o._statusCode, o.Payload)
}

func (o *PutInstancesIDDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PutInstancesIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
