{{- if .Values.grypeServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmclarity.grypeServer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.grypeServer.labels.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.grypeServer.serviceAccount.automountServiceAccountToken }}
{{- end -}}
