apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmclarity.gateway.name" . }}-hl
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "vmclarity.gateway.labels.standard" . | nindent 4 }}
  {{- if (not (empty .Values.gateway.service.annotations)) }}
  annotations: {{ .Values.gateway.service.annotations }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.gateway.service.ports.http }}
      targetPort: gateway-http
  selector: {{- include "vmclarity.gateway.labels.matchLabels" . | nindent 4 }}
