version: "3.9"

services:
  vmclarity-backend:
    image: ghcr.io/openclarity/vmclarity-backend:latest
    command: ["run"]
    container_name: vmclarity-backend
    ports:
      - "8888:8888"
    expose:
      - 8888
    volumes:
      - ~/vmclarity.db:/vmclarity.db
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SCANNER_CONTAINER_IMAGE: ghcr.io/openclarity/vmclarity-cli:latest
      TMPDIR: /tmp
      PROVIDER: Docker
      DATABASE_DRIVER: LOCAL
      LOCAL_DB_PATH: /vmclarity.db
      BACKEND_REST_HOST: vmclarity-backend
      EXPLOIT_DB_ADDRESS: http://exploit-db-server:1326
      GRYPE_SERVER_ADDRESS: grype-server:9991
      TRIVY_SERVER_ADDRESS: http://trivy-server:9992
      ALTERNATIVE_FRESHCLAM_MIRROR_URL: freshclam-mirror:80/clamav

  exploit-db-server:
    image: ghcr.io/openclarity/exploit-db-server:v0.2.3
    container_name: exploit-db-server
    expose:
      - "1326"

  trivy-server:
    image: docker.io/aquasec/trivy:0.41.0
    container_name: trivy-server
    command: ["server"]
    expose:
      - "9992"
    environment:
      TRIVY_LISTEN: 0.0.0.0:9992
      TRIVY_CACHE_DIR: /home/scanner/.cache/trivy

  grype-server:
    image: ghcr.io/openclarity/grype-server:v0.4.0
    command: ["run"]
    container_name: grype-server
    expose:
      - "9991"
    environment:
      DB_ROOT_DIR: /tmp/grype_server.db

  freshclam-mirror:
    image: ghcr.io/openclarity/freshclam-mirror:v0.2.0
    container_name: freshclam-mirror
    expose:
      - "80"

  ubuntu:
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    labels:
      scanconfig: test

networks:
  default:
    name: vmclarity
