// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/vmclarity/api/server/models"
)

// DeleteInstancesIDNoContentCode is the HTTP code returned for type DeleteInstancesIDNoContent
const DeleteInstancesIDNoContentCode int = 204

/*
DeleteInstancesIDNoContent Success

swagger:response deleteInstancesIdNoContent
*/
type DeleteInstancesIDNoContent struct {
}

// NewDeleteInstancesIDNoContent creates DeleteInstancesIDNoContent with default headers values
func NewDeleteInstancesIDNoContent() *DeleteInstancesIDNoContent {

	return &DeleteInstancesIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteInstancesIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteInstancesIDNotFoundCode is the HTTP code returned for type DeleteInstancesIDNotFound
const DeleteInstancesIDNotFoundCode int = 404

/*
DeleteInstancesIDNotFound Instance not found.

swagger:response deleteInstancesIdNotFound
*/
type DeleteInstancesIDNotFound struct {
}

// NewDeleteInstancesIDNotFound creates DeleteInstancesIDNotFound with default headers values
func NewDeleteInstancesIDNotFound() *DeleteInstancesIDNotFound {

	return &DeleteInstancesIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteInstancesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*
DeleteInstancesIDDefault unknown error

swagger:response deleteInstancesIdDefault
*/
type DeleteInstancesIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteInstancesIDDefault creates DeleteInstancesIDDefault with default headers values
func NewDeleteInstancesIDDefault(code int) *DeleteInstancesIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteInstancesIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete instances ID default response
func (o *DeleteInstancesIDDefault) WithStatusCode(code int) *DeleteInstancesIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete instances ID default response
func (o *DeleteInstancesIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete instances ID default response
func (o *DeleteInstancesIDDefault) WithPayload(payload *models.APIResponse) *DeleteInstancesIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete instances ID default response
func (o *DeleteInstancesIDDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteInstancesIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
