// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/vmclarity/api/server/models"
)

// GetInstancesIDOKCode is the HTTP code returned for type GetInstancesIDOK
const GetInstancesIDOKCode int = 200

/*
GetInstancesIDOK Success

swagger:response getInstancesIdOK
*/
type GetInstancesIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.InstanceInfo `json:"body,omitempty"`
}

// NewGetInstancesIDOK creates GetInstancesIDOK with default headers values
func NewGetInstancesIDOK() *GetInstancesIDOK {

	return &GetInstancesIDOK{}
}

// WithPayload adds the payload to the get instances Id o k response
func (o *GetInstancesIDOK) WithPayload(payload *models.InstanceInfo) *GetInstancesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get instances Id o k response
func (o *GetInstancesIDOK) SetPayload(payload *models.InstanceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInstancesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetInstancesIDDefault unknown error

swagger:response getInstancesIdDefault
*/
type GetInstancesIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetInstancesIDDefault creates GetInstancesIDDefault with default headers values
func NewGetInstancesIDDefault(code int) *GetInstancesIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetInstancesIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get instances ID default response
func (o *GetInstancesIDDefault) WithStatusCode(code int) *GetInstancesIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get instances ID default response
func (o *GetInstancesIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get instances ID default response
func (o *GetInstancesIDDefault) WithPayload(payload *models.APIResponse) *GetInstancesIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get instances ID default response
func (o *GetInstancesIDDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInstancesIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
