// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostInstancesContentAnalysisIDHandlerFunc turns a function with the right signature into a post instances content analysis ID handler
type PostInstancesContentAnalysisIDHandlerFunc func(PostInstancesContentAnalysisIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostInstancesContentAnalysisIDHandlerFunc) Handle(params PostInstancesContentAnalysisIDParams) middleware.Responder {
	return fn(params)
}

// PostInstancesContentAnalysisIDHandler interface for that can handle valid post instances content analysis ID params
type PostInstancesContentAnalysisIDHandler interface {
	Handle(PostInstancesContentAnalysisIDParams) middleware.Responder
}

// NewPostInstancesContentAnalysisID creates a new http.Handler for the post instances content analysis ID operation
func NewPostInstancesContentAnalysisID(ctx *middleware.Context, handler PostInstancesContentAnalysisIDHandler) *PostInstancesContentAnalysisID {
	return &PostInstancesContentAnalysisID{Context: ctx, Handler: handler}
}

/*
	PostInstancesContentAnalysisID swagger:route POST /instances/contentAnalysis/{id} postInstancesContentAnalysisId

Report a content analysis for a specific instance
*/
type PostInstancesContentAnalysisID struct {
	Context *middleware.Context
	Handler PostInstancesContentAnalysisIDHandler
}

func (o *PostInstancesContentAnalysisID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostInstancesContentAnalysisIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
