// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/vmclarity/api/server/models"
)

// PostInstancesContentAnalysisIDCreatedCode is the HTTP code returned for type PostInstancesContentAnalysisIDCreated
const PostInstancesContentAnalysisIDCreatedCode int = 201

/*
PostInstancesContentAnalysisIDCreated Instance content analysis successfully reported.

swagger:response postInstancesContentAnalysisIdCreated
*/
type PostInstancesContentAnalysisIDCreated struct {
}

// NewPostInstancesContentAnalysisIDCreated creates PostInstancesContentAnalysisIDCreated with default headers values
func NewPostInstancesContentAnalysisIDCreated() *PostInstancesContentAnalysisIDCreated {

	return &PostInstancesContentAnalysisIDCreated{}
}

// WriteResponse to the client
func (o *PostInstancesContentAnalysisIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostInstancesContentAnalysisIDNotFoundCode is the HTTP code returned for type PostInstancesContentAnalysisIDNotFound
const PostInstancesContentAnalysisIDNotFoundCode int = 404

/*
PostInstancesContentAnalysisIDNotFound Instance not found.

swagger:response postInstancesContentAnalysisIdNotFound
*/
type PostInstancesContentAnalysisIDNotFound struct {
}

// NewPostInstancesContentAnalysisIDNotFound creates PostInstancesContentAnalysisIDNotFound with default headers values
func NewPostInstancesContentAnalysisIDNotFound() *PostInstancesContentAnalysisIDNotFound {

	return &PostInstancesContentAnalysisIDNotFound{}
}

// WriteResponse to the client
func (o *PostInstancesContentAnalysisIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*
PostInstancesContentAnalysisIDDefault unknown error

swagger:response postInstancesContentAnalysisIdDefault
*/
type PostInstancesContentAnalysisIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostInstancesContentAnalysisIDDefault creates PostInstancesContentAnalysisIDDefault with default headers values
func NewPostInstancesContentAnalysisIDDefault(code int) *PostInstancesContentAnalysisIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PostInstancesContentAnalysisIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post instances content analysis ID default response
func (o *PostInstancesContentAnalysisIDDefault) WithStatusCode(code int) *PostInstancesContentAnalysisIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post instances content analysis ID default response
func (o *PostInstancesContentAnalysisIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post instances content analysis ID default response
func (o *PostInstancesContentAnalysisIDDefault) WithPayload(payload *models.APIResponse) *PostInstancesContentAnalysisIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post instances content analysis ID default response
func (o *PostInstancesContentAnalysisIDDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInstancesContentAnalysisIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
