// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutInstancesIDHandlerFunc turns a function with the right signature into a put instances ID handler
type PutInstancesIDHandlerFunc func(PutInstancesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutInstancesIDHandlerFunc) Handle(params PutInstancesIDParams) middleware.Responder {
	return fn(params)
}

// PutInstancesIDHandler interface for that can handle valid put instances ID params
type PutInstancesIDHandler interface {
	Handle(PutInstancesIDParams) middleware.Responder
}

// NewPutInstancesID creates a new http.Handler for the put instances ID operation
func NewPutInstancesID(ctx *middleware.Context, handler PutInstancesIDHandler) *PutInstancesID {
	return &PutInstancesID{Context: ctx, Handler: handler}
}

/*
	PutInstancesID swagger:route PUT /instances/{id} putInstancesId

Update Application.
*/
type PutInstancesID struct {
	Context *middleware.Context
	Handler PutInstancesIDHandler
}

func (o *PutInstancesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutInstancesIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
