name: CI
on:
  pull_request:
  merge_group:

env:
  GO_VERSION: "1.20"

jobs:
  api-verification:
    name: API Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate API code
        run: make api

      # This step will evaluate the repo status and exit if found changes
      # This should detect if the most up-to-date generated API code was pushed
      - name: Changes validation
        run: |
          [[ -z "$(git status --porcelain)" ]] || exit 1

  verification:
    needs: api-verification
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Run verification
        run: make check

  build:
    needs: verification
    name: Build
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      image_tag: ${{ github.sha }}
      push: false
      upload: false
