name: Main merge
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build_and_push:
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      image_tag: latest
      push: true
      use_release_repository: true
