name: Post Release
on:
  release:
    types: [published]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.modules.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Get modules
        id: modules
        run: |
          # shellcheck disable=SC2016
          echo "modules=$(find . -name go.mod -type f -print0 | xargs -0 awk '/module/ {print $2}' | jq -c -R '[.,inputs] | map(sub("^github.com\/openclarity\/vmclarity\/";""))')" >> "$GITHUB_OUTPUT"

  create_module_tags:
    needs:
      - prepare
    name: Create module tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ${{ fromJson(needs.prepare.outputs.modules) }}
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Create tags
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ matrix.tags }}/${{ github.ref_name }}',
              sha: context.sha
            })
