name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

permissions:
  packages: write
  contents: write

jobs:
  build_and_push:
    name: Build & Push
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      image_tag: ${{ github.ref_name }}
      push: true
      use_release_repository: true

  prerelease:
    needs:
      - build_and_push
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Delete tag
        # env:
        #   VERSION: ${{ github.ref_name }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin :${{ github.ref_name }}

      - name: Create and push module tags
        # env:
          # VERSION: ${{ github.ref_name }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make multimod-push-tags

      - name: Download artifacts
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: artifacts
          path: dist

      - name: Generate changelog
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make generate-release-notes

  main_release:
    needs:
      - prerelease
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - "containerruntimediscovery/types"
          - "containerruntimediscovery/server"
          - "containerruntimediscovery/client"
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "dist/*.tar.gz,dist/*.sha256sum,dist/bicep/vmclarity.json,dist/bicep/vmclarity-UI.json"
          bodyFile: "dist/CHANGELOG.md"
          draft: true
          name: "Release ${{ matrix.tags }}"
          updateOnlyUnreleased: true
          tag: ${{ matrix.tags }}/${{ github.ref_name }}
