name: Verification

on:
  workflow_call:

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # NOTE(chrisgacsal): Use actions/cache for caching Go dependency and build caches
          # as if provides better flexibility like setting the cache key which reduces cache misses significantly.
          cache: false
          go-version-file: 'go.mod'

      - name: Setup Go caching
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ github.ref_name }}-
            ${{ runner.os }}-go-${{ github.event.repository.default_branch }}-

      - name: Check license header
        run: make license-header

      - name: License cache
        uses: actions/cache@v3
        with:
          path: .licensei.cache
          key: licensei-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            licensei-${{ github.ref_name }}-
            licensei-${{ github.event.repository.default_branch }}-

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-cache

      - name: Vendor dependencies to retrieve licenses locally
        # Vendor deps before running https://github.com/goph/licensei
        # to avoid false-positives when modules GitHub repo could not be determined
        run: go mod vendor

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

  distributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Run linters for Cloudformation
        run: |
          make lint-cfn

      - name: Run linters for Helm
        run: |
          make lint-helm

      - name: Run linters for Azure/Bicep
        run: |
          make gen-bicep
          make lint-bicep
          [[ -z "$(git status --porcelain)" ]] || exit 1

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Github workflows
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          make lint-actions
          echo "::remove-matcher owner=actionlint::"

  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # NOTE(chrisgacsal): Use actions/cache for caching Go dependency and build caches
          # as if provides better flexibility like setting the cache key which reduces cache misses significantly.
          cache: false
          go-version-file: 'go.mod'

      - name: Setup Go caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ github.ref_name }}-
            ${{ runner.os }}-go-${{ github.event.repository.default_branch }}-

      - name: Cache golangci-lint cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.golangci.cache
          key: golangci-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golangci-${{ github.ref_name }}-
            golangci-${{ github.event.repository.default_branch }}-

      - name: Run linters
        env:
          GOLANGCI_LINT_CACHE: ${{ github.workspace }}/.golangci.cache
        run: |
          make lint-go

      - name: Run tests
        run: |
          make test
