name: Build & Push

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: 'Image tag to build and push.'
      push:
        required: false
        type: string
        description: 'If set to true, push the image.'
        default: false
      upload:
        required: false
        type: string
        description: 'If set to true, upload the image.'
        default: false

jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

  vmclarity-backend:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build output env var
        if: ${{ inputs.upload == 'true' }}
        run: |
          echo "OUTPUTS=type=docker,dest=/tmp/vmclarity.tar" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/openclarity/vmclarity-backend:${{ inputs.image_tag }}
          file: Dockerfile.backend
          push: ${{ inputs.push }}
          outputs: "${{ env.OUTPUTS }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Upload artifact
        if: ${{ inputs.upload == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: vmclarity
          path: /tmp/vmclarity.tar

  vmclarity-cli:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build output env var
        if: ${{ inputs.upload == 'true' }}
        run: |
          echo "OUTPUTS=type=docker,dest=/tmp/vmclarity-cli.tar" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/openclarity/vmclarity-cli:${{ inputs.image_tag }}
          file: Dockerfile.cli
          push: ${{ inputs.push }}
          outputs: "${{ env.OUTPUTS }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Upload artifact
        if: ${{ inputs.upload == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: vmclarity
          path: /tmp/vmclarity-cli.tar
