name: Lint PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          ignoreLabels: |
            ignore-semantic-pr
          types: |
            BREAKING
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
            release

          scopes: |
            general

            api
            cli
            containerruntimediscovery
            core
            orchestrator
            plugin
            provider
            scanner
            ui
            uibackend
            utils
            workflow

            aws
            azure
            docker
            gcp
            helm
            k8s

            ci
            deps
            e2e
            testenv

      # Leave a comment if linter reports an error
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼
            
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
      # Hide error message if the PR title has been fixed
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
        with:
          header: pr-title-lint-error
          delete: true
